### PR TITLE
Add support for contrib flags, featuring --comet

### PR DESCRIPTION
**Pull request by dsblank**
Ludwig is an excellent tool! We would love to be able to track, visualize, and manage Ludwig experiments in comet.ml.

We need a method of injecting imports for approved, third-party libraries into the Ludwig pipeline.

This PR adds a general method for third-parties to integrate their projects, at least as imports before the core libraries are imported. More sophisticated third-party connections could be made through hooks and callbacks. Such complexities are not implemented here. 

This PR also adds the flag `--comet` as a working example of such a third-party module. To use:

```shell
ludwig --comet 
``` 

This is useful while training. For example, the following code:

```shell
export COMET_PROJECT_NAME=ludwig 
ludwig experiment --comet \
  --data_csv reuters-allcats.csv \
  --model_definition_file model_definition.yaml
```
created the following: 

https://www.comet.ml/dsblank/ludwig/

If you can think of a less intrusive manner of inserting such code into the pipeline, please let us know.

### CODE REVIEW

**Comment by w4nderlust** [comment]
This looks great @dsblank ! Thanks so much for contributing this,
I will try to make it a little bit more general and commit here for you to take a look at it and comment.
We are going to release v0.1.1 soon, hopefully by the end of the week, and I'd like this to be part of it.

**Comment by dsblank** [comment]
Great! Let me know if there is anything else I can do.

**Comment by w4nderlust** [comment]
@dsblank Not sure if you get notifications, but here's a further commit i did and I commented at the bottom to get your feedback: https://github.com/uber/ludwig/commit/4030d13165eb840b22ea37bf8519c4848b9f130a

**Comment by dsblank** [comment]
Thanks! I'm following the whole repo, so I'm following along with your changes.

**Comment by dsblank** [comment]
I left some question, comments, and ideas on 4030d13.

**Comment by w4nderlust** [comment]
Thanks @dsblank will take a look shortly.

**Comment by w4nderlust** [comment]
Hi @dsblank , can I ask you a little favor? As we are getting ready to port Ludwig to TF2, it would be great if you could add a simple testcase in our integration suite for the Comet integration so that we can make sure everything works fine during the porting.
THanks

**Comment by dsblank** [comment]
@w4nderlust Sure, no problem! Comet already has a test suite for TF2, so everything should work smoothly for Ludwig + Comet. I'll take a look and see what we can do in your tests over the next week or so.

**Pull request merged**
