### PR TITLE
Updated beam search to use dynamic_decode

### PR DESCRIPTION
**Pull request by tgaddair**
This PR relies on https://github.com/tensorflow/addons/pull/2070.

### CODE REVIEW

**Comment by w4nderlust** [comment]
Looks good with the dynamic_decode. I guess the failing tests are solved by the pr for all_scores right?

**Comment by tgaddair** [comment]
Yes, that's correct.  Once that PR lands, we can incorporate the fix and land this.

**Comment by tgaddair** [comment]
TF Addons PR has landed, so once tonight's nightly is built, we can update and land this.

**Comment by tgaddair** [comment]
@w4nderlust this is ready to go if it looks good to you.

**Pull request merged**
