### PR TITLE
Substitute the use of lambda functions by list comprehension

### PR DESCRIPTION
**Pull request by milyiyo**
# Code Pull Requests

In this pull request, I propose to change the use of lambda functions in `test_neuropod.py` by list comprehension to gain a little more readability.

### CODE REVIEW

**Comment by tgaddair** [comment]
Looks like there was a new version of Pandas released today that broke the CI.  I'll take a look and let you know when a fix has landed.

**Comment by milyiyo** [comment]
> Looks like there was a new version of Pandas released today that broke the CI. I'll take a look and let you know when a fix has landed.

Thanks @tgaddair, for taking a look at it :)

**Comment by tgaddair** [comment]
Just landed the work around @milyiyo, can you rebase off master and force push?

**Comment by w4nderlust** [comment]
i think the code is fine, but yes please merge master or rebase so that CI can run and we are sure there are no issues.
Thanks for contributing anyway @milyiyo :)

**Review by tgaddair — APPROVED** [review]

**Pull request merged**
