### PR TITLE
Initial api example

### PR DESCRIPTION
**Pull request by jimthompson5802**
# Code Pull Requests

@msaisumanth This PR provides an example of addressing #560.  

Summary of changes:
* added  `examples` sub-directory. 
* added `examples/titanic` illustrating using the Ludwig Api for
   * model training
   * generating visualizations
   * demonstrating how to extract training statistics for custom analysis

### CODE REVIEW

**Comment by w4nderlust** [comment]
THank you this is really useful. Will likely do some minor changes and then merge.

**Comment by jimthompson5802** [comment]
Thank you for the feedback.  I'll submit a new PR for the second example (MNIST).  For the most part it will mirror what was done in the 'titanic' example.  The main difference will be generating more visualizations.  
I'm open to suggestions on what else to show in the api examples.  Just let me know.
If you can describe the "minor changes" you want to see, I'll make sure to include them in the MNIST example.  Minimize your work when it is time to merge. 
Or I can just wait to see what comes out in the final merge titanic.

**Comment by w4nderlust** [comment]
I finally took a deeper look at the example, it's pretty great!
A couple minor things to improve before merging:
- you can remove the the `model_definition = {...}` line as `model_definition` is no longer needed if you specify `model_definition_file`
- The notebook does a nice job at showing the learning curves together in one plot, But maybe you could use Ludwig's visualization API too, so that people know that ludwig already provides that functionality, what do you think?

**Comment by jimthompson5802** [comment]
@w4nderlust   I implemented these changes:
* remove the `model_definition-{...}` line in both `simple_model_training.py` and `multiple_model_training.py`
* I added the Ludwig visuazlize api example in the Jupiter notebook.  I did leave the generating the learning curves using the seaborn package.  If you don't want this second part, let me know and I'll remove it.

**Pull request merged**
