### PR TITLE
WIP: Update Hyperopt Tests for TF2 Porting & PySOTStrategy

### PR DESCRIPTION
**Pull request by kaushikb11**
Update Hyperopt Tests for TF2 Porting & PySOTStrategy.

### CODE REVIEW

**Comment by w4nderlust** [comment]
When running `test_hyperopt.py`, when the executor is `parallel` I get this error:

```
Fatal Python error: Aborted

Current thread 0x00007f1f6b673740 (most recent call first):
  File "/home/piero/dev/tf2venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_random_ops.py", line 713 in random_uniform
  File "/home/piero/dev/tf2venv/lib/python3.8/site-packages/tensorflow/python/ops/random_ops.py", line 295 in random_uniform
  File "/home/piero/dev/tf2venv/lib/python3.8/site-packages/tensorflow/python/ops/init_ops_v2.py", line 1067 in random_uniform
  File "/home/piero/dev/tf2venv/lib/python3.8/site-packages/tensorflow/python/ops/init_ops_v2.py", line 558 in __call__
  File "/home/piero/dev/ludwig/ludwig/models/modules/embedding_modules.py", line 68 in embedding_matrix
  File "/home/piero/dev/ludwig/ludwig/models/modules/embedding_modules.py", line 114 in embedding_matrix_on_device
...
```

**Comment by kaushikb11** [comment]
@w4nderlust : Yes, Tests are failing for `ParallelExecutor` (cpus & (PySOTStrategy for gpu)). Looking into it! Will update in some time.

**Comment by kaushikb11** [comment]
@w4nderlust : One issue was when I pass `gpus` = None, the `get_available_gpus` check for the gpus in the system. The GPUs are "claimed" by the call to `tensorflow.python.client.device_lib`. If this function is called in a child process that is subsequently killed, the GPUs are then available again and the program doesn't hang up. Pushed the changes.
The second Issue is running `ParallelExecutor` on cpus, not able to pickle certain Objects for multiprocessing. Have to check more into it.

**Comment by w4nderlust** [comment]
> @w4nderlust : One issue was when I pass `gpus` = None, the `get_available_gpus` check for the gpus in the system. The GPUs are "claimed" by the call to `tensorflow.python.client.device_lib`. If this function is called in a child process that is subsequently killed, the GPUs are then available again and the program doesn't hang up. Pushed the changes.
> The second Issue is running `ParallelExecutor` on cpus, not able to pickle certain Objects for multiprocessing. Have to check more into it and also the `Fatal Python error: Aborted` Error.

Got it, makes sense, although there may be a better / different way to check for available gpus that doesn't claim them... but if calling the function from the child process solves the problem, then that's fine :)

keep me posted if you figure out the other pieces. Specifically I can help figuring out the pickle part. My understanding is that the processes should just communicate the hyperparameters samples and the returned metrics, so I would inspect those objects, maybe there are some values that are tensorflow tesnors instead of being numpy arrays or things like that.

**Comment by kaushikb11** [comment]
1. Actually, it is the `lambda` function for the `category` type in `JointSpace`. [Link](https://github.com/uber/bayesmark/blob/master/bayesmark/space.py#L603). (Pickling Issue)

2. There's an IndexError for `update_batch` for `PySOTStrategy` running on ParallelExecutor:
`    i = np.argwhere(idx)[0].item()  # Pick the first index if there are ties
IndexError: index 0 is out of bounds for axis 0 with size 0` [Link](https://github.com/uber/bayesmark/blob/master/bayesmark/builtin_opt/pysot_optimizer.py#L144)

3. Coming across `Fatal Python error: Aborted` for `parallel` Executor only while running integration tests. It works fine when I run `hyperopt.py`. I have a hunch it could a memory release issue.

Also, it's so fun writing code with tests written for it :see_no_evil:

**Comment by w4nderlust** [comment]
@dme65 could you look into 1) and 2) please?

**Comment by dme65** [comment]
1) I'll make a PR in Bayesmark to get rid of the lambda call.
2) Do you have a way to reproduce this? I think I have an idea of what is going on and how to fix it, but I want to make sure I'm not missing any weird edge cases.

**Comment by kaushikb11** [comment]
> Do you have a way to reproduce this? I think I have an idea of what is going on and how to fix it, but I want to make sure I'm not missing any weird edge cases.

Yes, you could run the `hyperopt` integration tests with Parallel Executor & PySOT Strategy ([Link](https://github.com/uber/ludwig/blob/tf2_hyperopt/tests/integration_tests/test_hyperopt.py#L64)). @w4nderlust But I did some updates for hyperopt tests & `hyperopt_utils` in this PR. Also, working on fixing the `Fatal Python Error` at the moment for the tests.

**Comment by w4nderlust** [comment]
> > Do you have a way to reproduce this? I think I have an idea of what is going on and how to fix it, but I want to make sure I'm not missing any weird edge cases.
> 
> Yes, you could run the `hyperopt` integration tests with Parallel Executor & PySOT Strategy ([Link](https://github.com/uber/ludwig/blob/tf2_hyperopt/tests/integration_tests/test_hyperopt.py#L64)). @w4nderlust But I did some updates for hyperopt tests & `hyperopt_utils` in this PR, how should David go about it? Also, working on fixing the `Fatal Python Error` at the moment for the tests.

@dme65 can pull this branch with the command `hub pr checkout 776` ;) And also commit to the branch that will be created to add a commit to this PR.

**Comment by w4nderlust** [comment]
@dme65 and @kaushikb11 do you have any update on this?

**Comment by dme65** [comment]
I left a comment in the bayesmark PR and will look at the pySOT issue now.

**Comment by w4nderlust** [comment]
Merged this to keep tf2_hyperopt updated, but there are still issues to solve like the bayesmark stuff and the pysot stuff. We can create a new pr for those.

**Pull request merged**
