### PR TITLE
Fix visualize api doc parameter formatting

### LINKED ISSUE #547: Incorrect formatting of visualization api calls in Ludwig documentation
**Describe the bug**
Most visualization api parameters documentation are not correctly formatted.

**To Reproduce**
Example of incorrect formatting of documentation: https://uber.github.io/ludwig/api/visualization/#learning_curves
api_doc_incorrect_format

**Expected behavior**
Correct formatting of the parameter list

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOs 10:15
 - Version 10.15
- Python version N/A
- Ludwig version: 0.2.1

**Additional context**
I've researched and modified the module `code_doc_autogen.py` to correctly format the visualization api parameters.  In addition, minor updates were made to the docstring for functions in `visualize.py`.  Here is an example generated by the revised `code_doc_autogen.py`:
api_doc_correct_format

If this looks reasonable, I'm willing to finish up the work to correctly format the visualization api calls and submit a PR.    Any guidance will be appreciated.

### PR DESCRIPTION
**Pull request by jimthompson5802**
# Documentation Pull Requests

Fix #547

Note that the documentation HTML files are in `docs/` while the Markdown sources are in `mkdocs/docs`.

If you are proposing a modification to the documentation you should change only the Markdown files.

`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that file, first modify `ludwig/api.py` docstring, then run `mkdocs/code_docs_autogen.py`, which will create `mkdocs/docs/api.md` .

## Notes:
@w4nderlust  As noted in my posting from #547, I had to modify both the docstrings in `ludwig/visualize.py` and `mkdocs/code_doc_autogen.py` to correctly recreate `mkdocs/docs/api/visualization.md`

Per instructions in `mkdocs/README.md`, I tested the changes locally using the `mkdocs serve` command.  The visualization api documentation page rendered correctly.  I spot check several other pages that were not change to ensure correct rendering of the content.

### CODE REVIEW

**Comment by jimthompson5802** [comment]
@w4nderlust   Since I added a few lines of code to `mkdocs/code_doc_autogen.py`, this initiated code check by DeepSource.  I took a quick look at the issues flagged by DeepSource.  From what I can see, none of the issues are related to the half-a-dozen or so lines of code I added.  All the issues are with code that existed before my changes.  

I'm willing to make changes to that module such that it passes DeepSource checks.  Are there any constraints or limitations on what I can do to correct the issues?  Any design objectives, I need to keep in mind?

**Comment by mohi7solanki** [comment]
@jimthompson5802 DeepSource raises issues even if you have not introduced in your PR as we add new types of issues in our analyzer regularly.
- Mohit from DeepSource team.

**Comment by jimthompson5802** [comment]
@w4nderlust   I decided to take a stab at resolving the major issues flagged by deepsource.io.  From the original list of 23 major issues, I've whittled it down to 2 major issues.   Here is a summary of how I resolved the issues:

## The bulk of the issues were an internal function variable masking a variable by the same name in the outer scope
Screen Shot 2019-12-23 at 16 27 48
Screen Shot 2019-12-23 at 16 30 48

I resolved these by adding a leading underscore to the variable/parameter names in question, e.g.,  from 
* `function` to `_function`, 
* `method` to `_method`, 
* `confusion_matrix` to `_confustion_matrix`. 

## There were two issues where list comprehensions were flagged
Screen Shot 2019-12-23 at 16 29 54

These were resolved by replacing the list comprehension with a generator function.  Here is an example
### list comprehension version
```
subblocks.append('\n---\n'.join(
                    [render_function(method, _method=True) for method in
                     methods]))
```

### generator function version
```
# generator function to resolve deepsource.io major issue
                def generate_render_functions(_methods):
                    for m in _methods:
                        yield render_function(m, _method=True)

                subblocks.append('\n---\n'.join(generate_render_functions(methods)))
```

I understand why the list comprehension was flagged but in the context it is being used I don't see how this could be a performance issue because of the limited number of elements in the list.

## Use of len(Sequence) in a conditional test was flagged as an issue.
Screen Shot 2019-12-23 at 16 53 40

This was resolved by replacing 
```
if _method and len(_signature.args) > 0 and _signature.args[0] == 'self':
``` 
with 
```
if _method and _signature.args and _signature.args[0] == 'self':
```

This guidance comes directly from [PEP8 programming recommendations](https://www.python.org/dev/peps/pep-0008/#programming-recommendations)

```
> For sequences, (strings, lists, tuples), use the fact that empty sequences are false.
>
> Yes: if not seq:
>       if seq:
>
> No:  if len(seq):
>      if not len(seq):
```

## Remaining issue:  use of deprecated function `inspect.getargspec()`
Screen Shot 2019-12-23 at 16 20 21

I'm still working on this one.  Recommended replacement functions for `getargspec()` has a different return signature.  I'm assessing how to make the updates.

Any feedback will be appreciated.

**Comment by jimthompson5802** [comment]
The final deepsource.io major issues have been resolved.  Resolution for this issue was to replace the `inspect.getargspec()` function call with`inspect.getfullargspec()` function.  

Per instructions in `mkdocs/README.md`:

Successfully ran `python code_doc_autogen.py` to regenerate the api related documentation.

Tested the changes locally using the `mkdocs serve` command.  The visualization api documentation page rendered correctly.  I spot check several other pages that were not change to ensure correct rendering of the content.

From my perspective, this looks ready for your consideration to merge.

**Comment by w4nderlust** [comment]
looks good, thank you!

**Pull request merged**
