### PR TITLE
File-extension replacement

### PR DESCRIPTION
**Pull request by hemchander23**
Current method to check for HDF5/JSON file wouldn't work if the extension is in upper / mixed case. PR to overcome the same :) !

Fixes uber/ludwig/issues/64

Thanks,
Hem

### CODE REVIEW

**Comment by w4nderlust** [comment]
Hi Hem, thank you so much for submitting this PR. @msaisumanth was already working on this, he can actually build on top of your PR.
We use Pycharm's Format Code functionality to make sure indentation is consistent and that PEP8 specification are followed, can you please do a pass with it over the files involved in your commit and resubmit? (i see + without spaces around which is not PEP8 compliant for instance, the format code function would solve it).
@msaisumanth can you please test this out thoroughly?

**Comment by hemchander23** [comment]
Hi @w4nderlust , @msaisumanth,

I've made the changes using PyCharm this time.Could you please check?
Will adhere to the mentioned format in the future commits as well :) 

Thanks,
Hem

**Comment by w4nderlust** [comment]
@hemchander23 Thank you, now the code looks PEP-8 compliant. We are going to add this guideline in the developer guide. Will wait on @msaisumanth to do a final check before merging.

**Comment by msaisumanth** [comment]
Looks good!

**Comment by msaisumanth** [comment]
Thank you @hemchander23

**Comment by hemchander23** [comment]
My pleasure @msaisumanth @w4nderlust :)

**Pull request merged**
