### PR TITLE
Refactor text formatters

### PR DESCRIPTION
**Pull request by ydudin3**
Have tokenizer objects instead of functions so we can have encoders which require initialization to follow similar interface.

Test plan: unit and integration tests.

### CODE REVIEW

**Comment by msaisumanth** [comment]
The code is not that different for different languages. Why do we need a class for each language?

**Comment by msaisumanth** [comment]
We can use python closures or functools.partial to make it cleaner, unless we need classes so that people can extend it etc.

**Comment by w4nderlust** [comment]
> The code is not that different for different languages. Why do we need a class for each language?

This is the first refactoring stage, replicating 1:1 the functionality from before. I think this is good for now, later on we can improve it (of instance having one single class and passing the parameters coming from the preprocessing dictionary as parameters. Also at the moment we use a singleton nlp pipeline, something that can be replaced by a better mechanism now that instead of using functions we are using objects with separated call and init methods.

**Comment by w4nderlust** [comment]
I think this is fine @ydudin3 . The only thing i may consider doing differently is instead of creating a `tokenize()` method, maybe we can just use `__call__()` like we do for the encoders.
The other point, for the future, is that we may want to add empty init functions that collect kwargs for all classes, this to make sure that then we can pass the different preprocessing parameters that each of them need.

**Pull request merged**
