### PR TITLE
Add example code for k-fold cross validation function

### PR DESCRIPTION
**Pull request by jimthompson5802**
# Code Pull Requests

PR adds example code to run k-fold cv.  Two examples are provided.

## Classification Example
This example illustrates running the k-fold cv with the `ludwig experiment` cli. This example performs these functions:
* Download and prepare data for training and create a Ludwig model definition file from a pandas dataframe structure
* Execute `ludwig experiment` cli to run the 5-fold cross validation
* Display results from the 5-fold cross validation analysis

## Regression Example
A Jupyter notebook uses the Ludwig API to demonstrate running the k-fold cross validation analysis.  
* Download and prepare data for training and create a Ludwig model definition data structure from a pandas dataframe structure
* Use `experiment.kfold_cross_validate()` function  to run the 5-fold cross validation
* Display results from the 5-fold cross validation analysis

### CODE REVIEW

**Comment by w4nderlust** [comment]
Thank you so much, I did some minor renaming and refactoring before merging, butthis looks great!

**Comment by jimthompson5802** [comment]
@w4nderlust   You are most welcome.  With merging of the documentation updates and example code, I've done what I wanted to do for the k-fold cross validation function.  

I'm open to help with other features if you have a list.  Just be warned, I may bug you with a bunch of questions. :-)  Anyway, let me know if I can be of help.

**Comment by w4nderlust** [comment]
Thank you so much for all you work @jimthompson5802 ! It's really really appreciated.
As for other features to work on, it depends on how much you want to get you hands dirty in the internals. I've seen you proposing to work on the image models, and that's totally fine, otherwise we already started the planning to port to TF2 and we could use some help on that too. Whatever is most interesting for you.

**Comment by jimthompson5802** [comment]
@w4nderlust    Oops..I missed this reply before responding to the pre-trained image issue.  If I had seen this before, I would have responded differently to the image topic.  I apologize for causing you extra work in responding to my questions.

I'm certainly interested in learning more of Ludwig's internals.  If porting to TF2 is imminent, I'm interested helping with the TF2 port.  Helping with the port will provide me with better grounding on Ludwig's internal implementation.  This knowledge will be beneficial for any future work, such as the pre-trained image encoder.

To give you a better idea of in how I could help, here is my background.
* I work on Ludwig in my off-hours. 
* My experience with TF has been in mainly coding small demonstration programs, some in native TF api but more with Keras api.  This was for self-education and in support of helping data scientist at my day-job in figuring out how to use TF.
* I do my development in Docker containers on a mid-2014 MacBook Pro.

Let me know how I can help in the TF 2 port.

**Comment by w4nderlust** [comment]
Got it, I think your experience is relevant to this, also because I don't expect huge changes to happen in the models with the porting, what i expect to change is mostly the training loop.
So the porting can happen in different steps:

.1. Change all the imports to compat.v1 and try to run to TF2. If that works fine (as it should), then we can change the dependency to be TF2 and forget about TF1. The caveat here is that come thing, in particular the `contrib` package, have been moved out of TF into the TF addons package, so there could be things that don't work immediately out of the box
2. Remove all the `compat v1`, starting first from the training loop and a small set of features (making it work on just numerical and categorical features for instance).
3. Make it work for all the features.
4. Make it work for some corner cases (like the BERT encoder, or the sequence generator decoder)

So far I've been working on phase 1 as you can see by some commits around `compat.v1` and was planning to finish it by the end of this weekend. If you you want to contribute to this, I can start a PR tomorrow and we can work on that and chat inside it.

**Comment by jimthompson5802** [comment]
The 4 steps you outline make sense.  I'll look for the PR where we can start collaborating.

**Pull request merged**
