### PR TITLE
feat: timeseries preprocessing with stumpy

### PR DESCRIPTION
**Pull request by ifokeev**
That's the integration of `stumpy` matrix profile lib. 

https://github.com/TDAmeritrade/stumpy
https://stumpy.readthedocs.io/en/latest/Tutorial_STUMPY_Basics.html

To use this preprocessing, user has to add `preprocessing` section

```
preprocessing:
  matrix_profile:
    window_size: 10
```

into the `feature` from `model_definition`.

Also I added new `missing_value_strategy: drop_row` because matrix profile working with windows and there are no values for the `data[:window_size]` values.

I updated my codebase to use this logic too. Tested in our production environment.

Squash my commits if will merge, please.

### CODE REVIEW

**Comment by w4nderlust** [comment]
As you have noticed, we finally merged the tf2 porting in master. Would you be so kind to update this PR to work on the new master?

**Comment by ifokeev** [comment]
yeah will fix soon. Thank you all for `tf2`

**Comment by w4nderlust** [comment]
Thank you so much for this, and for the other bugfixes!

**Comment by ifokeev** [comment]
moved to https://github.com/uber/ludwig/pull/813/

**Pull request closed without merging**
