### PR TITLE
#357 fixed experiment name parameter

### PR DESCRIPTION
**Pull request by danicattaneob**
Added the parameter experiment_name in the method train from api.py and updated the docs with mkdocs.

### CODE REVIEW

**Comment by msaisumanth** [comment]
Thanks for the PR @danicattaneob. The code change looks good! 

@w4nderlust please take a look

**Comment by w4nderlust** [comment]
Thanks @danicattaneob , can you please remove the website stuff from the PR because you are probably using a different version of the dependencies and that makes for some confusion.
Leave Just `api.py`, and `api.md` I will update everything else.

**Comment by danicattaneob** [comment]
@w4nderlust Ready ;)

**Comment by w4nderlust** [comment]
Looks good, thanks for your contribution!

**Pull request merged**
