### PR TITLE
Add README_KR.md

### PR DESCRIPTION
**Pull request by rang21c**
# Documentation Pull Requests

This PR refers to issue #984.
Created README_KR.md, a Korean translation file for the main README.md file.
The part remaining in English in the translation is awkward when translated into Korean or easier to understand in English.

When I use Ludwig for the first time, i was surprised by its convenience and easiness. 
Those factors triggered me to translation work. 
Although some deep learning terms were not easy to translate into Korean, I truely think that it will give an opportunity for more Koreans to access Ludwig by with the translated files. 

Contact me if there's something wrong. 
Thank you!

### CODE REVIEW

**Comment by w4nderlust** [comment]
Thank you very much for this @rang21c it is truly appreciated!
I just moved the link around a little bit and added the flag :)
Merging it.

**Comment by w4nderlust** [comment]
@rang21c we updated substantially the readme. Would you consider helping out translating it again? This one is going to last for long :)

**Comment by rang21c** [comment]
@w4nderlust  Okay, but I'm a little busy because I'm working on two other projects.
So I think I can work on the translation in the summer. Maybe in July or August! :)

**Comment by w4nderlust** [comment]
@rang21c thanks for accepting to do it, it's very appreciated. I believe it would be pretty straightforward to adapt the previous one, it shouldn't take a lot of time :) Will ping you in a little while to remind about it. You are the only Korean speaker I know in the community, so again, I really appreciate your help :)

**Pull request merged**
